title: Favorite Aircraft Picks
description: A small Jekyll site for sharing favorite aircraft.
theme: null
markdown: kramdown
permalink: pretty

collections:
  picks:
    output: true
    permalink: /picks/:name/

defaults:
  - scope:
      path: ""
      type: "picks"
    values:
      layout: "pick"

exclude:
  - README.md
  - vendor/
